#!/usr/bin/env php
<?php
/**
 * @package        Arastta eCommerce
 * @copyright      Copyright (C) 2015-2016 Arastta Association. All rights reserved. (arastta.org)
 * @credits        See CREDITS.txt for credits and other copyright notices.
 * @license        GNU General Public License version 3; see LICENSE.txt
 */

if (php_sapi_name() !== 'cli') die('CLI Only');

use Symfony\Component\Console\Application;

define('AREXE', 1);

// Directories
$base = __DIR__;

define('DIR_BASE',          $base . '/');
define('DIR_ROOT', 			$base . '/');
define('DIR_INSTALL',     	DIR_ROOT . 'install/');
define('DIR_SYSTEM', 		DIR_ROOT . 'system/');
define('DIR_ADMIN', 		DIR_ROOT . 'admin/');
define('DIR_CATALOG', 		DIR_ROOT . 'catalog/');
define('DIR_CLI', 		    DIR_SYSTEM . 'console/');
define('DIR_VQMOD', 		DIR_ROOT . 'vqmod/');
define('DIR_IMAGE', 		DIR_ROOT . 'image/');
define('DIR_DOWNLOAD', 		DIR_ROOT . 'download/');
define('DIR_UPLOAD', 		DIR_ROOT . 'upload/');
define('DIR_CONFIG', 		DIR_SYSTEM . 'config/');
define('DIR_CACHE', 		DIR_SYSTEM . 'cache/');
define('DIR_MODIFICATION',	DIR_SYSTEM . 'modification/');
define('DIR_LOG', 			DIR_SYSTEM . 'log/');


if (!file_exists(DIR_SYSTEM.'vendor/autoload.php')) {
    die('You need to run Composer first. More details https://github.com/arastta/arastta');
}

if (!function_exists('is_installed')) {
    function is_installed()
    {
        if (!file_exists(DIR_ROOT . 'config.php')) {
            return false;
        }

        return true;
    }
}

// TODO: find a better way here
if (!defined('HTTP_SERVER')) {
    define('HTTP_SERVER', '');
}
if (!defined('HTTPS_SERVER')) {
    define('HTTPS_SERVER', '');
}

require_once(DIR_SYSTEM . 'library/client.php');

$admin = null;
$catalog = null;
$install = null;

if (is_installed()) {
    require_once(DIR_SYSTEM . 'startup.php');

    Client::setName('catalog');
    $catalog = new Catalog();
    $catalog->initialise();

    Client::setName('admin');
    $admin = new Admin();
    $admin->initialise();
} else {
    define('DIR_LANGUAGE', 		DIR_INSTALL . 'language/');
    define('DIR_TEMPLATE', 		DIR_INSTALL . 'view/theme/');

    $_SERVER['HTTP_HOST'] = '';

    // we need the $_SERVER['HTTP_HOST'] variable so that the define.php value loads correctly
    foreach ($argv as $argument) {
        if (strpos($argument, '--http_server') !== false) {
            $_SERVER['HTTP_HOST'] = str_replace('--http_server=', '', $argument);
            define('HTTP_SERVER', $_SERVER['HTTP_HOST']);
            define('HTTPS_SERVER', $_SERVER['HTTP_HOST']);
            break;
        }
    }

    Client::setName('install');

    require_once(DIR_SYSTEM . 'startup.php');

    $install = new Install();
    $install->initialise();
}

require_once(DIR_SYSTEM . 'library/command.php');

$console = new Application('Arastta CLI', '1.0');
$app = new Cli($console);

// set other apps for later usage
$app->set('admin', $admin);
$app->set('catalog', $catalog);
$app->set('install', $install);
$app->set('apps', array());

Client::setName('cli');

$app->initialise();

$console->run();
