<?php
/**
 * @package     Arastta eCommerce
 * @copyright   2015-2018 Arastta Association. All rights reserved.
 * @copyright   See CREDITS.txt for credits and other copyright notices.
 * @license     GNU GPL version 3; see LICENSE.txt
 * @link        https://arastta.org
 */

// Heading
$_['heading_title']          = 'Information';
$_['column_status']          = 'Status';

// Text
$_['text_list']              = 'Information List';
$_['text_add']               = 'Add Information';
$_['text_default']           = 'Default';
$_['text_preview']           = 'View Information';

$_['text_new_information_seo']  = 'Add a title and description to see how this information might appear in a search engine listing.';

// Column
$_['column_title']           = 'Information Title';
$_['column_sort_order']      = 'Sort Order';
$_['column_action']          = 'Action';

// Entry
$_['entry_title']            = 'Information Title';
$_['entry_description']      = 'Description';
$_['entry_store']            = 'Stores';
$_['entry_meta_title']       = 'Meta Tag Title';
$_['entry_meta_keyword']     = 'Meta Tag Keywords';
$_['entry_meta_description'] = 'Meta Tag Description';
$_['entry_seo_url']          = 'SEO URL';
$_['entry_bottom']           = 'Bottom';
$_['entry_status']           = 'Status';
$_['entry_sort_order']       = 'Sort Order';
$_['entry_layout']           = 'Layout Override';

// Help
$_['help_seo_url']           = 'Do not enter site name, just the information URL. Leave empty if you want to be generated by the system automatically based on information name.';
$_['help_bottom']            = 'Display in the bottom footer.';

// Error
$_['error_warning']          = 'Warning: Please check the form carefully for errors!';
$_['error_permission']       = 'Warning: You do not have permission to modify information!';
$_['error_title']            = 'Information Title must be between 3 and 64 characters!';
$_['error_description']      = 'Description must be more than 3 characters!';
$_['error_meta_title']       = 'Meta Title must be greater than 3 and less than 255 characters!';
$_['error_seo_url']          = 'SEO URL already in use!';
$_['error_account']          = 'Warning: This information page cannot be deleted as it is currently assigned as the store account terms!';
$_['error_checkout']         = 'Warning: This information page cannot be deleted as it is currently assigned as the store checkout terms!';
$_['error_affiliate']        = 'Warning: This information page cannot be deleted as it is currently assigned as the store affiliate terms!';
$_['error_return']           = 'Warning: This information page cannot be deleted as it is currently assigned as the store return terms!';
$_['error_store']            = 'Warning: This information page cannot be deleted as it is currently used by %s stores!';
