<?php
/**
 * @package        Arastta eCommerce
 * @copyright      Copyright (C) 2015-2016 Arastta Association. All rights reserved. (arastta.org)
 * @credits        See CREDITS.txt for credits and other copyright notices.
 * @license        GNU General Public License version 3; see LICENSE.txt
 */

// Heading
$_['heading_title']         = 'Manufacturers';

// Text
$_['text_success']          = 'Success: You have modified manufacturers!';
$_['text_list']             = 'Manufacturer List';
$_['text_add']              = 'Add Manufacturer';
$_['text_edit']             = 'Edit Manufacturer';
$_['text_default']          = 'Default';
$_['text_percent']          = 'Percentage';
$_['text_amount']           = 'Fixed Amount';
$_['text_preview']          = 'View Manufacturer';

// Column
$_['column_name']           = 'Manufacturer Name';
$_['column_sort_order']     = 'Sort Order';
$_['column_action']         = 'Action';
$_['column_status']         = 'Status';

// Entry
$_['entry_name']             = 'Manufacturer Name';
$_['entry_description']      = 'Description';
$_['entry_meta_title']       = 'Meta Tag Title';
$_['entry_meta_keyword']     = 'Meta Tag Keywords';
$_['entry_meta_description'] = 'Meta Tag Description';
$_['entry_seo_url']          = 'SEO URL';
$_['entry_store']            = 'Stores';
$_['entry_image']            = 'Image';
$_['entry_sort_order']       = 'Sort Order';
$_['entry_status']           = 'Status';
$_['entry_layout']           = 'Layout Override';
$_['entry_type']             = 'Type';

// Help
$_['help_seo_url']           = 'Do not enter site name, just the manufacturer URL. Leave empty if you want to be generated by the system automatically based on manufacturer name.';

// Error
$_['error_permission']       = 'Warning: You do not have permission to modify manufacturers!';
$_['error_name']             = 'Manufacturer Name must be between 2 and 64 characters!';
$_['error_meta_title']       = 'Meta Title must be greater than 3 and less than 255 characters!';
$_['error_seo_url']          = 'SEO URL already in use!';
$_['error_product']          = 'Warning: This manufacturer cannot be deleted as it is currently assigned to %s products!';
