<?php
/**
 * @package     Arastta eCommerce
 * @copyright   2015-2018 Arastta Association. All rights reserved.
 * @copyright   See CREDITS.txt for credits and other copyright notices.
 * @license     GNU GPL version 3; see LICENSE.txt
 * @link        https://arastta.org
 */

// Heading
$_['heading_title'] = 'Posts';

// Text
$_['text_blog_setting']  = 'Settings';
$_['text_blog_category'] = 'Categories';
$_['text_blog_post']     = 'Posts';
$_['text_blog_comment']  = 'Comments';
$_['text_preview']       = 'View Post';
$_['text_yes']           = 'Yes';
$_['text_no']            = 'No';
$_['text_please_select'] = '--- Please Select ---';
$_['text_new_post_seo']  = 'Add a title and description to see how this post might appear in a search engine listing.';
$_['text_applicable']    = 'Applicable';
$_['text_applied']       = 'Applied';

// Column
$_['column_image']      = 'Image';
$_['column_name']       = 'Name';
$_['column_category']   = 'Category';
$_['column_date_added'] = 'Date Added';
$_['column_comments']   = 'Comments';
$_['column_status']     = 'Status';
$_['column_viewed']     = 'Page Views';
$_['column_sort_order'] = 'Sort Order';

// Button
$_['button_category_add'] = 'Add New Category';

// Entry
$_['entry_name']                  = 'Name';
$_['entry_seo_url']               = 'SEO URL';
$_['entry_meta_title']            = 'Meta Title (Page Title)';
$_['entry_meta_keyword']          = 'Meta Tag Keywords';
$_['entry_meta_description']      = 'Meta Tag Description';
$_['entry_description']           = 'Description';
$_['entry_short_description']     = 'Short Description';
$_['entry_short_description_h']   = 'This will be used as the blog summary when the blog post is listed in categories, related posts or latest posts.';
$_['entry_tags']                  = 'Tags';
$_['entry_category']              = 'Category';
$_['entry_related']               = 'Related Posts';
$_['entry_date_available']        = 'Date Published';
$_['entry_status']                = 'Status';
$_['entry_store']                 = 'Stores';
$_['entry_image']                 = 'Image';
$_['entry_author']                = 'Author';
$_['entry_keyword']               = 'SEO URL';
$_['entry_sort_order']            = 'Sort Order';
$_['entry_allow_comment']         = 'Allow Comment';
$_['entry_featured']              = 'Featured';
$_['entry_comment_permission']    = 'Comment Permission';
$_['entry_comment_need_approval'] = 'Comment Need Approval';
$_['entry_with_selected']         = 'With selected';
$_['entry_layout']                = 'Layout Override';
$_['entry_tag']                   = 'Tags';
$_['entry_all_tags']              = 'All Tags';
$_['entry_view_all']              = 'View All';
$_['entry_all_category']          = 'All Categories';

// Help
$_['help_seo_url']  = 'Do not enter site name or category, just the post URL. Leave empty if you want to be generated by the system automatically based on post name.';
$_['help_category'] = '(Autocomplete)';
$_['help_tag']      = '(Autocomplete)';

// Error 
$_['error_warning']       = 'Warning: Please check the form carefully for errors!';
$_['error_name']          = 'Blog Title must be between 3 and 64 characters!';
$_['error_store']         = 'Warning: This blog page cannot be deleted as its currently used by %s stores!';
$_['error_required_data'] = 'Required Data has not been entered. Check for field errors!';
$_['error_seo_url']       = 'SEO URL already in use!';
$_['error_tag']           = 'Warning: Already added this tag!';
$_['error_tag_empty']     = 'Warning: Please check the tag must be greater than 1!';
$_['error_add_same_tag']  = 'Opps, You have already use this tag!';
